### ISSUE TITLE
2.10.0 x86_64-unknown-linux-gnu puts DRG into Sandbox mode

### ISSUE THREAD

**Issue by hydrox** [trumank/mint#115]
Installing mods via mint adds and activates the chosen mods, but doesn't seem to disable the mod.io integration and thus puts the game into Sandbox mode.
![Bildschirmfoto vom 2024-01-04 15-12-23](https://github.com/trumank/mint/assets/113484/ba28ad3f-fc47-4939-afef-380cebe50c0f)
![Bildschirmfoto vom 2024-01-04 15-12-06](https://github.com/trumank/mint/assets/113484/06fde9a5-2d8d-47f2-a8ff-c428d386ffa6)
![20240104151411_1](https://github.com/trumank/mint/assets/113484/afa0a0c7-3ef3-4cbb-b064-0ff9b75d24db)

**Comment by hydrox** [comment]
![Bildschirmfoto vom 2024-01-04 16-25-48](https://github.com/trumank/mint/assets/113484/12ec35b7-0f26-48d6-950a-3df554f6156c)
[steam-548430.log](https://github.com/trumank/mint/files/13832060/steam-548430.log)

**Comment by trumank** [comment]
I'm not sure why `X3DAudio1_7.dll` is showing as `builtin`. Perhaps it changed with a different version of proton? 

`Deep Rock Galactic\\FSD\\Binaries\\Win64\\X3DAudio1_7.dll" at 00007FA00A2A0000: builtin`

You should be able to add `WINEDLLOVERRIDES="X3DAudio1_7=b"` before `%command%` in the steam launch options to make it load the native DLL.

**Comment by hydrox** [comment]
Adding that option prevents DRG from running at all.

**Comment by trumank** [comment]
Another option is setting the override in the wine prefix directly, which is most easily done using protontricks: `protontricks --no-bwrap 548430 winecfg`. Add new override for `X3DAudio1_7` if one doesn't already exist and set it to native, then builtin.
![image](https://github.com/trumank/mint/assets/1144160/e4ae46c2-e3ff-48aa-b83e-0ccb1eb5a887)

If the game still doesn't launch then please upload another proton log if one gets created

**Comment by hydrox** [comment]
Thank you, with that change it now started properly with the mods installed and mod.io disabled
