### ISSUE TITLE
libssl Incompatibility on SteamOS and Ubuntu 22.04/23.10

### ISSUE THREAD

**Issue by turboxgts** [trumank/mint#122]
Title. If I'm remembering correctly, SteamOS and Ubuntu 22.04 at the time of writing use OpenGL 3.x and don't have the required OpenGL 1.x that Mint uses.

**Comment by trumank** [comment]
Did you get an error message saying this (and can you paste it verbatim)? Operating systems don't ship with just a single version of OpenGL but a wide range and both of those should be supported on pretty much any modern hardware. I'd also be a bit surprised if egui were using OpenGL 1, but I don't know enough about its backend to say for sure.

**Comment by turboxgts** [comment]
Sorry for taking so long, kinda forgot to take care of this. Happened to do a system wipe and upgrade so I don't have the things manually upgraded again
On ubuntu 23.10(.1?), I get this error by manually running the appimage through the terminal (nothing happens if I run via doubleclicking the file):
`error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`
I'll post a second comment when I get to doing it on my steam deck

**Comment by turboxgts** [comment]
Also, I forgot which thing was wrong, so I'll be renaming the issue to reflect the actual problem

**Comment by turboxgts** [comment]
Just confirmed, it does the same on Steam Deck

**Comment by trumank** [comment]
Should be fixed in ec75ebf63d3d9901b5fdd56a4fe7f442b14b8554, pending next release

**Comment by Saigaiii** [comment]
> Should be fixed in [ec75ebf](https://github.com/trumank/mint/commit/ec75ebf63d3d9901b5fdd56a4fe7f442b14b8554), pending next release

Is there by chance an eta on when that release will happen? Glad to see it fixed.
