### ISSUE TITLE
Mint Instantly Closing

### ISSUE THREAD

**Issue by Okibon** [trumank/mint#128]
Hadn't played DRG in a while, open DRG , mods are gone, open mint, instantly closes (image is what it shows for 1/10 of a second before closing).
Some context is that I moved DRG onto an SSD when this first happened, however in an attempt to fix this, I tried reinstalling the game back onto the same drive as mint, and also reinstalling mint, but it still instantly closes itself.
![image](https://github.com/trumank/mint/assets/62333062/b4234a43-ada7-427d-8ee4-fa602bdb7e53)

**Comment by jieyouxu** [comment]
Could you share the full log? For windows it should be somewhere like
`C:\Users\<username>\AppData\Roaming\drg-mod-integration\data\drg-mod-integration.log`

**Comment by Okibon** [comment]
Sure, 

2024-02-04T22:21:07.779358Z DEBUG drg_mod_integration: tracing subscriber setup
2024-02-04T22:21:07.779542Z  INFO drg_mod_integration: writing logs to `C:\Users\okiii\AppData\Roaming\drg-mod-integration\data\drg-mod-integration.log`
2024-02-04T22:21:07.779556Z DEBUG drg_mod_integration: logging setup complete
2024-02-04T22:21:07.779843Z DEBUG drg_mod_integration: tokio runtime created
2024-02-04T22:21:07.779943Z DEBUG drg_mod_integration: args: Args { action: None }

**Comment by jieyouxu** [comment]
Does the log never reach something like

```
2023-09-17T00:57:22.945493Z  INFO drg_mod_integration::gui: config dir = C:\Users\<username>\AppData\Roaming\drg-mod-integration\config
2023-09-17T00:57:22.945952Z  INFO drg_mod_integration::gui: cache dir = C:\Users\<username>\AppData\Local\drg-mod-integration\cache
```

If that is the case, it might be for some reason we can't determine the default config/cache/data directories:

```
let dirs = args
        .appdata
        .as_ref()
        .map(Dirs::from_path)
        .unwrap_or_else(Dirs::default_xdg)?;
```

**Comment by Okibon** [comment]
"Does the log never reach something like" nope, what I sent is the whole log
"If that is the case, it might be for some reason we can't determine the default config/cache/data directories:"
not smart enough to know what that means but im assuming there's a fix?

**Comment by jieyouxu** [comment]
> not smart enough to know what that means but im assuming there's a fix?

We're gonna have to investigate a bit more as to why this happens on Windows. Could you please provide the Windows version?

**Comment by Okibon** [comment]
Windows 11, (been using it for months beforehand with no issues)

**Comment by jieyouxu** [comment]
> Windows 11, (been using it for months beforehand with no issues)

Yeah, something is definitely weird going on here, cuz I was developing mint on Windows 11 too and never ran into this particular issue. @trumank any guesses?

**Comment by trumank** [comment]
It's failing to parse some config/cache file as seen in the first line of the screenshot. Hard to say what's happening without seeing the files, but you can move/delete them to have them get re-created. They can be found at:
`%appdata%/drg-mod-integration`
`%localappdata%/drg-mod-integration`

`%appdata%/drg-mod-integration/config/mod_data.json` contains all the mod profiles so you may way to keep that and try to recover it if that's the file causing issues, but everything in the cache can get deleted.

**Comment by jieyouxu** [comment]
@Okibon we could try to recover your old config and mod data files, which is like what Truman said, possibly located at `%AppData%\drg-mod-integration\config\config.json` and `%AppData%\drg-mod-integration\config\mod_data.json`. If you could try to find those and upload those, it would be very helpful to us to help debug the issue and we may be able to recover them.

**Comment by jieyouxu** [comment]
If you also run into this, the solution might require you to nuke all of your mint data:

- `C:\Users\<username>\AppData\Roaming\drg-mod-integration\config`
- `C:\Users\<username>\AppData\Local\drg-mod-integration\cache`
- `C:\Users\<username>\AppData\Roaming\drg-mod-integration\data`

Okibon's cache.json was corrupted in addition to mod_data.json, but I don't know how that happened.
