### ISSUE TITLE
ureq error: discord attachment/oo2core_9_win64.dll: status code 403

### ISSUE THREAD

**Issue by TonyTouhou** [trumank/mint#134]
can't install mods because of this

**Comment by jieyouxu** [comment]
cc @trumank that link has expired (I believe either Discord removed the linked content, or Discord has set an expiry date on their links now).

**Comment by trumank** [comment]
Fixed with recent repak update, pending next release:
7c5d5bf9f2521b970b8ddb29e744b4c53ba8828b 
https://github.com/trumank/repak/commit/02b1ae4264fc8d9febb3fddb5e07e1eb516d0640#diff-0eb694ca9bad297df14835065ab02df36bbcc10722ea5dbc62b095a06e9fbb2fL13-R66

**Comment by TonyTouhou** [comment]
nice!

**Comment by AkomTo** [comment]
So, i had same issue several days ago, and as it turns out "hazard persistence enjoyer" were main source of problems, try to delete it from the mod list by pressing on minus near it, and then press "install mods".
This should fix your problem, or if you dont have this exact mod, problem could hide in other mods, just try to install them one by one if you still having an issue.
Also instead of hazard persistence enjoyer, try to use simpleQOL.

**Comment by trumank** [comment]
For reference in the meantime: https://github.com/trumank/mint/issues/98#issuecomment-1751971077

> That DLL is required for paks compressed with Oodle (there are only a handful of them I've run into for DRG). Can you download it manually and place it next to the integrator exe? That way the integrator won't have to fetch it itself.
> 
> There are some alternative ways to find the DLL if you search:
> MD5: `f2db01967705b62aecef3cd3e5a28e4d`
> SHA1: `4bcc73614cb8fd2b0bce8d0f91ee5f3202d9d624`

**Comment by baixiongnull** [comment]
I don't know code. I cannot understand what's the meaning of this：
There are some alternative ways to find the DLL if you search:
MD5: f2db01967705b62aecef3cd3e5a28e4d
SHA1: 4bcc73614cb8fd2b0bce8d0f91ee5f3202d9d624
SHA256: 19452ae1abae65e1305d3818354d4fae7b1200294322f0d9c6d5ddeb7bd9f978
Download and place next to the exe with name oo2core_9_win64.dll and it will get loaded

What exactly I should do to fix the error?
I need the file, where can i get it?
And where should i put it into?

**Comment by Connor-jt** [comment]
might be worthwhile pushing out a release that implements the solution, else you'll probably get new issues opened every time someone runs into this problem (especially because people don't look through closed issues)

**Comment by Vulpain** [comment]
whenever I install mods with mint, I always get a mod named "MODS_P" in my mod list in game. It shows that it is deprecated, and it's sandbox as well so that forces me to open a sandbox save even though I'm only using verified mods.

**Comment by Jorde5212** [comment]
> ⚡⚡ To everyone installing Mission HUD: If you got the error "Connection Failed" "cannot get the file -- oo2core_9_win64.dll", this solution will exactly fix it.
> 
>     1. download this dll >> https://www.dllme.com/dll/files/udeh
> 
>     2. change its name with "oo2core_9_win64.dll"
> 
>     3. put it into the file folder where "drg_mod_integration.exe" is
>        Then you can install this mission hud mod successfully.

This fixed my problem. Just installed Mint 0.2.10

**Comment by Kevinik** [comment]
> > ⚡⚡ To everyone installing Mission HUD: If you got the error "Connection Failed" "cannot get the file -- oo2core_9_win64.dll", this solution will exactly fix it.
> > ```
> > 1. download this dll >> https://www.dllme.com/dll/files/udeh
> > 
> > 2. change its name with "oo2core_9_win64.dll"
> > 
> > 3. put it into the file folder where "drg_mod_integration.exe" is
> >    Then you can install this mission hud mod successfully.
> > ```
> 
> This fixed my problem. Just installed Mint 0.2.10

Same with me Thank You!
