### ISSUE TITLE
Recent mod.io API changes prevent the addition of new mods to Mint.

### ISSUE THREAD

**Issue by DraedonDev** [trumank/mint#139]
Hi, I already talked about this with memtransmute on Practical DRG, but placing this here at his request.

Mod.io seems to have changed their API sometime today. It prevents the addition of new mods but allows already installed mods to be updated from the cache. The error for adding new mods is:

> HTTPS status client error (403 Forbidden): You must possess administrator privileges to apply the (visible-in) filter value.

Pasting memtransmute's thoughts on Discord here, verbatim:

> in mint we used a filter-in check to see if a mod is visible
mod.io may have tightened access to that api endpoint
so only admins can see that now
which would explain the forbidden status

Hopefully this is an easy fix on your end. I know you're all working on a large update, but it might be best to push a hotfix for the time being, or post the current build as a release candidate on Discord for others to test. I really don't want to tell you all what I think you should do about this, considering I'm no programmer/contributor, but I'd like to offer my thoughts regardless.

Best wishes to you all :)

**Comment by jieyouxu** [comment]
mod.io reverted the API changes from their end so this should no longer be an issue.
