### ISSUE TITLE
MS Store version crashes with latest version from master

### ISSUE THREAD

**Issue by Doddleee** [trumank/mint#140]
Cloned and built latest version from the master branch 
When trying to loads mods into the MS store version of Deep Rock Galactic, I get to the initial startup screen after which the game force closes with error 0xe06d7363 

Tested/confirmed with an identical modlist on an older version of MINT which had no issues
![image_2024-02-27_170017439](https://github.com/trumank/mint/assets/161493299/c932cc50-a10b-4057-9b8d-950b897ef7bf)

**Comment by jieyouxu** [comment]
Does it still crash if you only install a simple mod?

Please also share your mods list that triggers this crash.

**Comment by Doddleee** [comment]
Crashes even with just Mod Hub installed - I had dm'd assembly about it, he said it's sort of a known issue (something with the menus being slightly different on the MS store version) but that he hadn't gotten around to testing it. Advised me to make a post on here anyway
