### ISSUE TITLE
HTTP status client error (404 Not Found):The requested mod id could not be found.

### ISSUE THREAD

**Issue by 995441437** [trumank/mint#150]
I don't know why this happened, I have deleted all the expired mods

```
[31mERROR[0m [2mdrg_mod_integration::gui::message[0m[2m:[0m modio::Error {
    kind: Status(
        404,
    ),
    source: Error {
        code: 404,
        error_ref: 14000,
        message: "The requested mod id could not be found.",
        errors: None,
    },
}
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: BaseThreadInitThunk
  22: RtlUserThreadStart
```

**Comment by jieyouxu** [comment]
Please share your mods list. You can copy the mod URLs using the button at the top right corner.

**Comment by 995441437** [comment]
> Please share your mods list. You can copy the mod URLs using the button at the top right corner.

https://mod.io/g/drg/m/auto-recall-sentry#3796501
https://mod.io/g/drg/m/bluearchivecaretaker-to-decagrammaton#3796620
https://mod.io/g/drg/m/text-commands-wheel#1148865
https://mod.io/g/drg/m/ping-longer#1146573
https://mod.io/g/drg/m/real-gatling-stats#2340795
https://mod.io/g/drg/m/server-name#2584012
E:\SteamLibrary\steamapps\common\Deep Rock Galactic\FSD\Content\mod管理器大厅服务器地区筛选.pak
https://mod.io/g/drg/m/displays-all-monster-outlines#3488377
https://mod.io/g/drg/m/remove-m1000-classic-particles#3371079
https://mod.io/g/drg/m/azusas-drak-25-sound-mod#1956385
https://mod.io/g/drg/m/combined-presets#2814623
https://mod.io/g/drg/m/bosco-retooled#1813426
https://mod.io/g/drg/m/booloblast#1122623
https://mod.io/g/drg/m/bosco-chan-icon-replacer#2723280
https://mod.io/g/drg/m/bosco-chan-model-replacement-anime#2931108
https://mod.io/g/drg/m/bosco-chan-stand#2195549
https://mod.io/g/drg/m/better-bolt-indicator#2100272
https://mod.io/g/drg/m/improved-fire-bomber-projectile-visibility#3187876
https://mod.io/g/drg/m/reduced-cloud-opacity-remake#2145331
https://mod.io/g/drg/m/extra-loading-tips-chinese#2815359
https://mod.io/g/drg/m/faster-pickaxe#3204323
https://mod.io/g/drg/m/better-pickaxe-recharge-widget#1149745
https://mod.io/g/drg/m/retrograde-mod-spawner#1399744
https://mod.io/g/drg/m/better-pickaxe1#3422106
https://mod.io/g/drg/m/sekiro-danger-for-heightened-senses#2771775
https://mod.io/g/drg/m/miracles-assignment-reroll#2787974
https://mod.io/g/drg/m/blue-screen-bedrock#2226039
https://mod.io/g/drg/m/dude-wheres-my-mule#2834035
https://mod.io/g/drg/m/dynamic-weapon-and-lighting-modifications#3484905
https://mod.io/g/drg/m/overcharger-indicator#3513258
https://mod.io/g/drg/m/increased-crosshair-visibility#3146742
https://mod.io/g/drg/m/classic-cartoon-dash-sound-replacer#2070263
https://mod.io/g/drg/m/boss-diggy-player-icons#1162310
https://mod.io/g/drg/m/all-previous-campaigns-available#3484419
https://mod.io/g/drg/m/lowpoly#2434442
https://mod.io/g/drg/m/damage-numbers#3311283
https://mod.io/g/drg/m/instant-enemy-healthbar#3451243
E:\SteamLibrary\steamapps\common\Deep Rock Galactic\FSD\Content\Paks\秒切枪1.1(装于MOD管理器)\秒切枪1.1(客_线上替换)_兼容所有武器修改MOD\qieqiang.pak
https://mod.io/g/drg/m/who-done-it-button-mod#2292814
https://mod.io/g/drg/m/streamsuit-5000-tools#2155079
https://mod.io/g/drg/m/improved-flare-gun#2625115
https://mod.io/g/drg/m/glowing-equipment#1751567
https://mod.io/g/drg/m/glowing-equipment-add-on#1862858
https://mod.io/g/drg/m/monster-quantity-display#3363051
https://mod.io/g/drg/m/display-stabber-vines-hp#2909311
https://mod.io/g/drg/m/brighter-objects-add-on#1720132
https://mod.io/g/drg/m/aichis-beer-selector#2965513
https://mod.io/g/drg/m/build-inspector#2101319
https://mod.io/g/drg/m/custom-difficulty#1861561
https://mod.io/g/drg/m/sandbox-utilities#1897251
https://mod.io/g/drg/m/no-pickaxe-movement-penalty#1328395
https://mod.io/g/drg/m/lbs-base-kit#2986917
https://mod.io/g/drg/m/sprint-by-default-hold-to-walk#2152235
https://mod.io/g/drg/m/motd-stattrack#1145532
https://mod.io/g/drg/m/goldchunksbegone#2424882
https://mod.io/g/drg/m/death-marker#3035859
https://mod.io/g/drg/m/combined-resources#1863656
https://mod.io/g/drg/m/ammo-percentage-indicator#2613099
https://mod.io/g/drg/m/mod-hub#1792770
https://mod.io/g/drg/m/better-cracking-boots#3096163
https://mod.io/g/drg/m/born-ready-hud-popup#2905192
https://mod.io/g/drg/m/better-contrasting-twins-recolored-arbalest#2525496
https://mod.io/g/drg/m/blue-flamethrower#1230219
https://mod.io/g/drg/m/weapon-heat-crosshair#1634437
https://mod.io/g/drg/m/platform-placement-preview#1674997
https://mod.io/g/drg/m/modified-gunner-shield-effect#3029397
https://mod.io/g/drg/m/clutterbegone#2434441
https://mod.io/g/drg/m/buyable-missions#1962912
https://mod.io/g/drg/m/promotion-levels-after-legendary-3-indicator#2369777
https://mod.io/g/drg/m/closer-promotion-terminal-updated#2092879
https://mod.io/g/drg/m/aichis-indicator-ui-pt1-class-tools#2932283
https://mod.io/g/drg/m/customizable#2478655
https://mod.io/g/drg/m/stock-and-bosco-weapon-paintjob-unlocker#1807375
https://mod.io/g/drg/m/brighter-objects#1179441
https://mod.io/g/drg/m/googly#2101850
https://mod.io/g/drg/m/better-spectator-reloaded#1877135
https://mod.io/g/drg/m/pingtotext#2273035
https://mod.io/g/drg/m/remove-all-particles-but-weaponsntools#1034644
https://mod.io/g/drg/m/health-and-shield-numbers#1664873
https://mod.io/g/drg/m/better-unknown-horror-indicator#2503544
https://mod.io/g/drg/m/better-explosion-range-indicator#1831206
https://mod.io/g/drg/m/alternate-player-list-ui#2553961
https://mod.io/g/drg/m/customizable-ally-outlines#1533299
https://mod.io/g/drg/m/enemy-radar-mk2#2837897
https://mod.io/g/drg/m/drglib#1034237
https://mod.io/g/drg/m/no-ragdolls#2121639
https://mod.io/g/drg/m/custom-vanity-framework#2432311
https://mod.io/g/drg/m/simplemissiontimer#1605951
https://mod.io/g/drg/m/live-mission-stat-tracker#1636619
https://mod.io/g/drg/m/rancors-rig-hud#1769472
https://mod.io/g/drg/m/miracle-mod-manager#1582325

**Comment by 995441437** [comment]
@jieyouxu 您可以看到我发的url吗？Can you see the URL I sent?

**Comment by jieyouxu** [comment]
> @jieyouxu 您可以看到我发的url吗？Can you see the URL I sent?

Try updating your local mod.io cache? That button is located on the bottom right corner.
试试更新本地mod.io缓存，按下Update Cache? 右下角按钮

**Comment by 995441437** [comment]
> > @jieyouxu 您可以看到我发的url吗？Can you see the URL I sent?
> 
> Try updating your local mod.io cache? That button is located on the bottom right corner. 试试更新本地mod.io缓存，按下Update Cache? 右下角按钮

@jieyouxu 我已经尝试更新了，但是会报错，明天我再打开电脑试一试
I have tried to update, but there will be an error. I will open my computer tomorrow and try again

**Comment by jieyouxu** [comment]
> @jieyouxu 我已经尝试更新了，但是会报错，明天我再打开电脑试一试 I have tried to update, but there will be an error. I will open my computer tomorrow and try again

Alright. If it still doesn't work tomorrow, try deleting the cache under `%AppData%\Local\drg-mod-integration\cache`.
明天你再试试，不行的话把缓存(`%AppData%\Local\drg-mod-integration\cache`)给清了再试

If that still doesn't work, I can provide a build from latest master where we improved error reporting, which should tell you which specific mod triggered the error.
再不行我可以给你提供一份master分支上最新的版本，我们改进了报错机制，如果是具体一个mod有问题应该会显示哪个mod出错

**Comment by jieyouxu** [comment]
I tried your mod list locally and it did not trigger any errors, so it's not your mod list. Has to be the cache or something.
我试了你的mod列表，在我本地是没问题的 估计是缓存之类的问题

**Comment by 995441437** [comment]
> I tried your mod list locally and it did not trigger any errors, so it's not your mod list. Has to be the cache or something. 我试了你的mod列表，在我本地是没问题的 估计是缓存之类的问题

@jieyouxu 我尝试删除缓存，但还是更新失败。能发给我master版本吗？我的邮箱是15515306921@163.com
I tried to delete the cache, but the update still failed. Can you send me the master version? My email is 15515306921@163.com

**Comment by 995441437** [comment]
> I tried your mod list locally and it did not trigger any errors, so it's not your mod list. Has to be the cache or something. 我试了你的mod列表，在我本地是没问题的 估计是缓存之类的问题

我将所有的mod删除了，然后重新输入URL，这样可以正常更新mod了。不知道哪里出现了问题，如果有新版本的软件，我很高兴进行试用
I have deleted all mods and re entered the URL so that the mods can be updated normally. I don't know where the problem is. If there is a new version of the software, I am happy to try it out

**Comment by jieyouxu** [comment]
Glad to hear you were able to solve this problem. I'm going to close this issue as resolved for now, if you encounter the same problem, feel free to open the issue again.
很高兴听到你的问题得到了解决，我们一般避免主动提供非稳定版本（除非必要），如果你再次遇到这个问题，欢迎重新打开这个issue
