### ISSUE TITLE
Crashes a couple seconds after loading in to the spacerig

### ISSUE THREAD

**Issue by Revalopod** [trumank/mint#152]
### The UE4 crash reporter tool says:

Fatal error: [File:Unknown] [Line: 1334] Failed to find function OnHubContext in MI_SpawnMods_C /Game/Maps/SpaceRig/LVL_SpaceRig.LVL_SpaceRig:PersistentLevel.MI_SpawnMods_C_2147481391

### My modlist is:

<img width="558" alt="modlist" src="https://github.com/trumank/mint/assets/162626927/34c80e4c-c599-439b-98e5-cca02a6fd254">

Ps. These mods didn't crash for me when using Mod.io. The only difference here is using Unified Ui instead of ModHub.
Edit: It still crashes even with all mods disabled. Only when uninstalling it stopped crashing. Now back to Mod.io and all my mods are enabled there and it's not crashing.

**Comment by Buckminsterfullerene02** [comment]
Use this pak file instead, it fixes the issue

[unified-ui.zip](https://github.com/trumank/mint/files/14538593/unified-ui.zip)

**Comment by jieyouxu** [comment]
Closing as this seems to be an UUI-related issue.
