### ISSUE TITLE
failing to remove x3daudio_7.dll

### ISSUE THREAD

**Issue by RumiAura** [trumank/mint#156]
![image_2024-03-26_164805918](https://github.com/trumank/mint/assets/147914818/043f0d2f-562c-460e-adaa-ef5b3d3adf7c)
i had a problem with the dll file getting detected as a trojan before but allowed it after searching it up, now it cant seem to remove that file either, i can also install and update cache just fine

**Comment by trumank** [comment]
You need to add an exemption to your antivirus or otherwise fix it interfering with this file (which is used by mint).
