### ISSUE TITLE
VRG doesn't seem to work with mint

### ISSUE THREAD

**Issue by Okjuiceman** [trumank/mint#158]
The mod can be properly installed, but once installed it runs desktop mode instead of steam vr mode, I tried using my older 2nd pc without mint and the VRG mod worked though steam vr with no issues.

**Comment by trumank** [comment]
Does it work using official mod integration on the same PC? I've never set it up myself but looks like there is a launch flag and some config files that need to be installed and the same would need to be done if using mint: https://mod.io/g/drg/m/vrg

**Comment by Okjuiceman** [comment]
I realized i missed one letter on the override step once i fixed that it works now on both pc with mint on aka i was being dumb
