### ISSUE TITLE
Game freezes when trying to load

### ISSUE THREAD

**Issue by raffel080108** [trumank/mint#160]
The game freezes on either the "Initializing..." screen or a black screen when I launch. This is not just slow loading, when I load with standard mod loading then I load within 2-3 seconds max, I let it sit for 10-20+ seconds multiple times and nothing happened. I tried re-installing and re-launching multiple times
I can load this exact modlist perfectly fine with the regular modding integration

Mod list:
https://mod.io/g/drg/m/azusas-hurricane-sound-mod#1886547
https://mod.io/g/drg/m/azusas-zhukov-sound-mod#1899215
https://mod.io/g/drg/m/azusas-bulldog-sound-mod#1884235
https://mod.io/g/drg/m/azusas-pgl-sound-mod#1884206
https://mod.io/g/drg/m/azusas-breach-cutter-sound-mod#1899114
https://mod.io/g/drg/m/azusas-boomstick-sound-mod#1884204
https://mod.io/g/drg/m/azusas-brt7-sound-mod#1905144
https://mod.io/g/drg/m/azusas-stubby-sound-mod#1884191
https://mod.io/g/drg/m/azusas-sludge-pump-sound-mod#1939610
https://mod.io/g/drg/m/azusas-subata-sound-mod#1886545
https://mod.io/g/drg/m/azusas-drak-25-sound-mod#1956385
https://mod.io/g/drg/m/azusas-cryo-cannon-sound-mod#1924125
https://mod.io/g/drg/m/azusas-wave-cooker-sound-mod#2022939
https://mod.io/g/drg/m/azusas-crspr-sound-mod#1919614
https://mod.io/g/drg/m/azusas-coil-gun-sound-mod#2022913
https://mod.io/g/drg/m/azusas-lead-storm-sound-mod#1905159
https://mod.io/g/drg/m/azusas-epc-sound-mod#1961406
https://mod.io/g/drg/m/azusas-boltshark-sound-mod#2022934
https://mod.io/g/drg/m/azusas-shard-diffractor-sound-mod#2022943
https://mod.io/g/drg/m/deep-dive-secondaries-on-normal-missions-season4#3122386
https://mod.io/g/drg/m/wheres-dottys-head#2898235
https://mod.io/g/drg/m/modified-gunner-shield-effect#3029397
https://mod.io/g/drg/m/rancors-rig-hud#1769472
https://mod.io/g/drg/m/weapon-heat-crosshair#1634437
https://mod.io/g/drg/m/promotion-levels-after-legendary-3-indicator#2369777
https://mod.io/g/drg/m/unique-status-icons-w-hud-elements-sticky-icons#3122703
https://mod.io/g/drg/m/sprint-by-default-hold-to-walk#2152235
https://mod.io/g/drg/m/vanity-search#2443134
https://mod.io/g/drg/m/tweek-the-goblin-intern-mc-re-voice#1527667
https://mod.io/g/drg/m/platform-placement-preview#1674997
https://mod.io/g/drg/m/platform-effect-indicator#1824234
https://mod.io/g/drg/m/pingtotext#2273035
https://mod.io/g/drg/m/sgg-framework-files#3096846
https://mod.io/g/drg/m/rgb-bots#2325531
https://mod.io/g/drg/m/no-camera-shake#1158572
https://mod.io/g/drg/m/no-gasp-on-low-ox#1160813
https://mod.io/g/drg/m/live-mission-stat-tracker#1636619
https://mod.io/g/drg/m/miracle-mod-manager#1582325
https://mod.io/g/drg/m/iron-will-duration#3418805
https://mod.io/g/drg/m/frozen-impact-particles-fps-fix#2285617
https://mod.io/g/drg/m/improved-class-icons#3361779
https://mod.io/g/drg/m/health-and-shield-numbers#1664873
https://mod.io/g/drg/m/hardhat-dotty#2016954
https://mod.io/g/drg/m/fast-forging-continued#3350207
https://mod.io/g/drg/m/enemy-radar#2442215
https://mod.io/g/drg/m/death-marker#3035859
https://mod.io/g/drg/m/damage-text#1599642
https://mod.io/g/drg/m/display-stabber-vines-hp#2909311
https://mod.io/g/drg/m/cave-leech-loudencer#3451090
https://mod.io/g/drg/m/clear-notifications#3387181
https://mod.io/g/drg/m/drglib#1034237
https://mod.io/g/drg/m/customizable-ally-outlines#1533299
https://mod.io/g/drg/m/closer-promotion-terminal-updated#2092879
https://mod.io/g/drg/m/caretaker-with-doomers-music#2190731
https://mod.io/g/drg/m/brighter-objects#1179441
https://mod.io/g/drg/m/caretaker-phases-custom-music-framework#2172271
https://mod.io/g/drg/m/boss-hp-bar-for-big-enemies#3074337
https://mod.io/g/drg/m/build-inspector#2101319
https://mod.io/g/drg/m/biomebugs#2530578
https://mod.io/g/drg/m/better-explosion-range-indicator#1831206
https://mod.io/g/drg/m/better-downed-icon#1160850
https://mod.io/g/drg/m/born-ready-hud-popup#2905192
https://mod.io/g/drg/m/better-unknown-horror-indicator#2503544
https://mod.io/g/drg/m/ammo-percentage-indicator-e#2671319
https://mod.io/g/drg/m/better-contrasting-twins-recolored-arbalest#2525496
https://mod.io/g/drg/m/mod-hub#1792770
https://mod.io/g/drg/m/alternate-player-list-ui#2553961
https://mod.io/g/drg/m/a-better-modding-menu#2247462
https://mod.io/g/drg/m/beast-master-tracker#3449780´

**Comment by trumank** [comment]
See #44

**Comment by raffel080108** [comment]
Thanks, the patched mod file in the mentioned issue seems to be working perfectly
