### ISSUE TITLE
How do i completely uninstall a mod?

### ISSUE THREAD

**Issue by the-phuctran** [trumank/mint#161]
How do I uninstall a mod including my user setting of that mod? Every time I uninstall a mod and reinstall, the old setting profile of the mod that I used before keep showing without reset to the default setting of it like what I saw in the first time installed.

**Comment by trumank** [comment]
Mint does not manage mod settings (nor does the official modding system). Mods typically save their settings to `Deep Rock Galactic/FSD/Saved/SaveGames/Mods`.
