### ISSUE TITLE
Chrome marks windows zip as suspicious.

### ISSUE THREAD

**Issue by SGamerXxX** [trumank/mint#162]
Chrome marks Windows Zip as suspicious. Avast marked exe as malware. Had it downloaded before but all of a sudden it the exe file from mint got deleted, and when I tried to unzip it, it came up with access denied. (I am the administrator) Deleted the file to re-download it from here and now it either won't download the latest or go back, a version, Chrome marks it as suspicious. I don't know what to think.

**Comment by trumank** [comment]
There's nothing I can do about anti-virus flagging the executable. It's a hobby project used by a relatively small amount of people and applies patches to the game via DLL injection which naturally looks really suspicious to anti-virus software.

**Comment by SGamerXxX** [comment]
Well, at least I know it's not a virus, now to see if I can re-download it again somehow...Thanks
