### ISSUE TITLE
locol

### ISSUE THREAD

**Issue by huiruhefanying** [trumank/mint#167]
Hello author, why did I encounter the problem of being unable to import local mods. My English is not very good, it's machine translation, there may be some problems
![2024-04-20_18 52 03](https://github.com/trumank/mint/assets/167617950/f673b94a-4be4-4d64-8b22-e7c319ad2912)
![2024-04-20_18 52 03](https://github.com/trumank/mint/assets/167617950/bf847a4a-c4f6-4622-bef6-585758740780)

**Comment by trumank** [comment]
It doesn't let you click and drag the mod into the window? Try copying the mod file path and pasting it instead e.g. `C:\path\to\the_mod.zip`

**Comment by huiruhefanying** [comment]
The problem has been solved, you are really amazing
