### ISSUE TITLE
Would Uninstalling Mods or MINT itself Affect my save file?

### ISSUE THREAD

**Issue by Lioju98** [trumank/mint#170]
Example. I if i download a mod that affects spawn rate for events and cargo crates, if i deleted this mod or Mint itself after claiming these rewards, would it affect my save file and turn it into sandbox?
Sorry if this isn't the appropriate place to post questions

**Comment by trumank** [comment]
The only time a sandbox save file gets created is when explicitly doing so via the sandbox save creation menu when using a sandbox mod through the official integration.
