### ISSUE TITLE
Game crashes after trying to join a game

### ISSUE THREAD

**Issue by Plagueinjector** [trumank/mint#213]
Sometimes whenever i join a random game or i myself create one, i seem to crash when it starts and you are loading in.
It started to happen right after S5 release.

The crash code is this:

Fatal error: [File:Unknown] [Line: 403] Failed to find parameter collection buffer with GUID '87105FEF4F79B6A293EA5F88C2ABB74D'. Currently 4 listed default instances: 0x000001F3ACF3D480: MPC_GlobalMaterialParameters: DF9CB07940EED20878332E9F7C2788F5 0x000001F3A5501D80: MPC_PingLocation: F1DBEFA3485D94B7D4CF11B7153444F5 0x000001F394BC2080: MPC_DD_Scanner_Mat_Parameters: 9AF14675466CC5B2704397ADE5782183 0x000001F411D97B40: MPC_Burn_Dissolve: 7185498C4C77E8CD180BD98EE5A41851

FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
FSD_Win64_Shipping
kernel32
ntdll

Can anyone help me fix this?

**Comment by jieyouxu** [comment]
This is not a mint issue. The crash trace looks to me like you have Brighter Objects and/or Brighter Objects (Add-on) installed. Try disabling or remove them from your mods list then "Install Mods" again.
