### ISSUE TITLE
Using Mint to install Fumo Mod causes the game's sound effects equalizer to be too loud.

### ISSUE THREAD

**Issue by star-whisper9** [trumank/mint#215]
Mod: [Fumo DRG Mod](https://mod.io/g/drg/m/fumo-drg-mod)

When subscribing to this mod through mod.io, everything works fine.
When obtained and installed through Mint, the sound of the game's "sound effects" category will be very loud, but the sound effect volume in the game settings is not adjusted. The most obvious is the sound of the Autocannon gun or the rock music in the Jukebox, which will directly break the sound.
This problem still exists when manually copying the pak package to the Paks folder without installing it through Mint.

**Comment by trumank** [comment]
The mod itself is broken and only "works" using the official modding implementation because it fails to load the assets that modify sound volume.
