### ISSUE TITLE
This mod manager creates a virus infected x3*audio.dll file in the game directory

### ISSUE THREAD

**Issue by jpeaglesandkatz** [trumank/mint#223]
Please explain as this is constantly flagged and deleted by multiple scans.

**Comment by jieyouxu** [comment]
See https://github.com/trumank/mint/issues/175, https://github.com/trumank/mint/issues/162, https://github.com/trumank/mint/issues/156, https://github.com/trumank/mint/issues/115, https://github.com/trumank/mint/discussions/222. Nothing we can do about your AV flagging the generated hook as suspicious.
