### ISSUE TITLE
Approved mods installed via MINT force a quarantine save in the game.

### ISSUE THREAD

**Issue by Freeman256** [trumank/mint#231]
Description of the problem.
The problem is specified in the description. I will describe my actions in more detail:
I downloaded the mod files with the .pak extension. Unpacked MINT ver [[0.2.10] - 2023-08-18](https://github.com/trumank/mint/releases/tag/v0.2.10), launched it, moved the "approved" mod files to the MINT window, clicked "install mods" and "update cache". When the game starts, the mods really work, but the game forcibly creates this stupid quarantine save. The game indicates that it does not like the fact that in folder ...\Deep Rock Galactic\FSD\Content\Paks there are other files with the .pak extension in addition to the main game file (this other file is created by MINT, which contains all the mods thrown into MINT).

Expected solution.
"Approved" mods that are installed using MINT should not force the game to create a quarantine save. In the version of the game with Season 4, this file with mods was also created, but the game was not at all confused, and it did not create a quarantine save.

Please fix it.

**Comment by eebssk1** [comment]
This is not MINT's fault.
You need to either disable modio in advanced settings of game launch config so that modio no longer checks for suspicious pak in game files.
Or if you don't want to disable modio,then you can trick it by mimic the pak name, changing the pak made by MINT to something like "FSD-WindowsNoEditor099.pak"

**Comment by jieyouxu** [comment]
No, this smells like your antivirus (Windows Defender or whatever) removed the DLL hook that mint relies on to disable the in-game modding system which includes the sandbox check: see https://github.com/trumank/mint/issues/175, https://github.com/trumank/mint/issues/162, https://github.com/trumank/mint/issues/156, https://github.com/trumank/mint/issues/115, https://github.com/trumank/mint/discussions/222, #223.

**Comment by Freeman256** [comment]
Thank you very much for your help! Disabling mods with the launch parameter "-disablemodding" helped me. Now both mods work and quarantine saving is not forced! Antivirus ESET Smart Security was enabled when installing mods.

**Comment by eebssk1** [comment]
> No, this smells like your antivirus (Windows Defender or whatever) removed the DLL hook that mint relies on to disable the in-game modding system which includes the sandbox check: see https://github.com/trumank/mint/issues/175, https://github.com/trumank/mint/issues/162, https://github.com/trumank/mint/issues/156, https://github.com/trumank/mint/issues/115, https://github.com/trumank/mint/discussions/222, #223.

Probably You can add a check that verify if the dlls is still  in place at second launch and notify the users if they are gone then ask to check AV or disable modio manually.

**Comment by jieyouxu** [comment]
> Thank you very much for your help! Disabling mods with the launch parameter "-disablemodding" helped me. Now both mods work and quarantine saving is not forced! Antivirus ESET Smart Security was enabled when installing mods.
> 
> By the way, is there any way to remove the quarantine mark from a save?
> 
> If you think it's necessary, you can close this issue.

Note that mint's hook is *responsible* for disabling the in-game modding system and thus the regular save / sandboxed save distinction. So if the hook was properly installed, you would not have *needed* `-disablemodding` and the game would not have prompted you to use a sandbox save. AFAICT currently you are loading the merged mod pak via the legacy modding method, not via mint's loading method!

> I have a suggestion: maybe it's worth adding a code to MINT that, when used, will display a message in the game itself that "Mods were installed using MINT, auto-update of mods via mod.io is disabled." If this is not possible, then maybe it's worth making a pop-up window in the MINT program itself when installing mods with a text like "Don't forget to use the launch parameter -disablemodding when starting the game"

On master branch, mint already replaces the in-game modding menu.

**Comment by Freeman256** [comment]
Yes, indeed, in the quarantine of my antivirus there is a file from the game folder: x3daudio1_7.dll

**Comment by jieyouxu** [comment]
Closing as this is an antivirus problem, nothing we can do in our end.
