### ISSUE TITLE
oodle hash mismatch expected: 4bcc73614cb8fd2b0bce8d0f91ee5f3202d9d624 got: 94cbe010b822bfa2aa0fe46658917238a85caf7f

### ISSUE THREAD

**Issue by gabrielioanpavel** [trumank/mint#238]
Happens when I try to install the mods. Mod list for reference attached.
![image](https://github.com/user-attachments/assets/32b54e11-8672-4957-9627-0c0fac7ef435)

**Comment by trumank** [comment]
You managed to find some other version of `oo2core_9_win64.dll` so mint will refuse to load it for security reasons. See https://github.com/trumank/mint/issues/134
