### ISSUE TITLE
Does not run on Steam Deck

### ISSUE THREAD

**Issue by slice-the-idiot** [trumank/mint#242]
when i try running the program through desktop or game mode, i get nothing, while when i open it through konsole, i get this
` error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

**Comment by Saigaiii** [comment]
Yup I had this issue as well. Never found a fix. Even running the windows version under wine brings up an error when trying to put the api token with a:

"tcp connect error: OS Error 10051 (FormatMessagew() returned error 317) (os error 10051)"

**Comment by trumank** [comment]
Duplicate of https://github.com/trumank/mint/issues/122
