### ISSUE TITLE
(QUESTION) mod restriction bypass?

### ISSUE THREAD

**Issue by dataesucsdeek** [trumank/mint#249]
am i able to use certain mods like 3x ammo, without the game restricting me?

**Comment by dataesucsdeek** [comment]
i really, really want this to be do-able. cmon, its just ammo???

**Comment by Connor-jt** [comment]
> am i able to use certain mods like 3x ammo, without the game restricting me?

yeah with this tool

**Comment by dataesucsdeek** [comment]
alright, ive already found my answer to this bc i said "fuck it" and tested it, it worked!
