### ISSUE TITLE
Gas Fix being redundant after S5 update

### ISSUE THREAD

**Issue by BlueCookieFrog** [trumank/mint#252]
I've noticed you are applying some kind of workaround for gas fix in mint.
Season 5 finally fixed the issue, so I believe this is no longer needed.

**Comment by trumank** [comment]
I've heard the patch finally made it into the game. Looks like it is indeed the same patch I proposed.
![image](https://github.com/user-attachments/assets/71bb1b82-7268-4fb4-9c16-75787e5ecafc)
