### ISSUE TITLE
Oodle compression

### ISSUE THREAD

**Issue by trumank** [trumank/mint#33]
There are a very small amount of mods on mod.io using oodle compression which `repak` does not support well on Windows or at all on Linux due to it requiring a proprietary DLL:

https://mod.io/g/drg/m/random-mission-selection
https://mod.io/g/drg/m/better-pickaxe-recharge-widget
https://mod.io/g/drg/m/text-commands-wheel
https://mod.io/g/drg/m/hazard-persistence-enjoyer

Depending on how widespread oodle ends up being on mod.io, it may make sense to look into better support, or just creating patched versions of these mods without oodle.

**Comment by trumank** [comment]
Fixed with repak update 7c5d5bf9f2521b970b8ddb29e744b4c53ba8828b

**Comment by tgmatt** [comment]
Any chance of a working release that contains this code? Latest available version throws an Oodle error when attempting to install, and master is currently broken.
